spring.application.name=finance-tracker

# ---------- H2 Database ----------
#spring.datasource.url=jdbc:h2:file:./data/financetracker;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.url=jdbc:h2:mem:financetracker
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ---------- Server ----------
#server.port=8080
server.port=${PORT:8080}


# ---------- JWT ----------
# 256-bit base64 secret used to sign tokens. Change this in production and load from env var.
app.jwt.secret=${JWT_SECRET:U29tZVN1cGVyU2VjcmV0S2V5Rm9ySldUU2lnbmluZ1RoYXRJc0xvbmdFbm91Z2hGb3JIUzUxMg==}

app.jwt.expiration-ms=86400000

# ---------- Logging ----------
logging.level.org.springframework.security=INFO
